print("Willkommen zur Mathestunde!")
print()

print("Additionen:")
print(f"1 + 1 = {1 + 1}")
print(f"2 + 1 = {2 + 1}")
print(f"5 + 3 = {5 + 3}")
print(f"3 + 2 = {3 + 2}")
print()

print("Subtraktionen:")
print(f"4 - 2 = {4 - 2}")
print(f"6 - 3 = {6 - 3}")
print(f"8 - 7 = {8 - 7}")
print(f"3 + 2 = {5 - 1}")
print()

print("Multiplizieren:")
print(f"2 · 3 = {2 * 3}")
print(f"3 · 4 = {3 * 4}")
print(f"2 · 8 = {2 * 8}")
print(f"5 · 4 = {5 * 4}")
print()

print("Dividieren:")
print(f"8 : 2 = {8 / 2}")
print(f"4 : 1 = {4 / 1}")
print(f"12 : 3 = {12 / 3}")
print(f"10 : 5 = {10 / 5}")
print()

print("Potenzieren:")
potenzieren = range(1, 10)
for x in potenzieren:
    print(f"2^{x} = {2 ** x}")
print()

print("Mit eigenen Zahlen rechnen: (+)")
a = input(print("Was ist deine erste Zahl? "))
b = input(print("Was ist deine zweite Zahl? "))
print()
print(f"Dein Ergebnis lautet: {a + b}")
print()
print("Danke für eure Aufmerksamkeit!")